Bad / Best practices add
CiscoDevNet/code-exchange-repo-template pull request #6
Opened 2020-07-28 16:40 UTC by oborys

2020-07-28 20:21 UTC, eckelcu requested changes
It would be better to make these changes to ./manual-sample-repo/README.md instead of to ./README.md.
I would also put the best practices first, and state bad practices as best practices when possible. For example, instead a bad practice of omitting NOTICE file can be a best practice of including a NOTICE file.

2020-07-29 09:27 UTC, oborys commented
@eckelcu in this commit 903ce3e I move practices to manual-sample-repo/README.md, move/change item regarding notice to Best practices

2020-07-30 19:05 UTC, eckelcu approved these changes

2020-07-30 19:06 UTC, merged

2020-07-30 19:07 UTC, eckelcu commented
Thanks for making the changes. I really appreciate this contribution, and other will as well.